export const EVENT_DISPATCHER = Symbol('EVENT_DISPATCHER');
export const USERS_BASE_REPOSITORY = Symbol('USERS_BASE_REPOSITORY');
export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const REFLECTIVE_PROFILES_BASE_REPOSITORY = Symbol('REFLECTIVE_PROFILES_BASE_REPOSITORY');
export const REFLECTIVE_PROFILES_REPOSITORY = Symbol('REFLECTIVE_PROFILES_REPOSITORY');
export const CHAT_AGENT = Symbol('CHAT_AGENT');
export const CONVERSATION_MESSAGE_HISTORY_BASE_REPOSITORY = Symbol(
  'CONVERSATION_MESSAGE_HISTORY_BASE_REPOSITORY'
);
export const CONVERSATION_MESSAGE_HISTORY_REPOSITORY = Symbol(
  'CONVERSATION_MESSAGE_HISTORY_REPOSITORY'
);
export const USER_DAILY_USAGES_BASE_REPOSITORY = Symbol('USER_DAILY_USAGES_BASE_REPOSITORY');
export const USER_DAILY_USAGES_REPOSITORY = Symbol('USER_DAILY_USAGES_REPOSITORY');
export const USER_SUBSCRIPTIONS_BASE_REPOSITORY = Symbol('USER_SUBSCRIPTIONS_BASE_REPOSITORY');
export const USER_SUBSCRIPTIONS_REPOSITORY = Symbol('USER_SUBSCRIPTIONS_REPOSITORY');
export const PROVIDER_EVENTS_BASE_REPOSITORY = Symbol('PROVIDER_EVENTS_BASE_REPOSITORY');
export const PROVIDER_EVENTS_REPOSITORY = Symbol('PROVIDER_EVENTS_REPOSITORY');
export const PAYMENT_ORDERS_BASE_REPOSITORY = Symbol('PAYMENT_ORDERS_BASE_REPOSITORY');
export const PAYMENT_ORDERS_REPOSITORY = Symbol('PAYMENT_ORDERS_REPOSITORY');
