export const EVENT_DISPATCHER = Symbol('EVENT_DISPATCHER');
export const USERS_BASE_REPOSITORY = Symbol('USERS_BASE_REPOSITORY');
export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const REFLECTIVE_PROFILES_BASE_REPOSITORY = Symbol('REFLECTIVE_PROFILES_BASE_REPOSITORY');
export const REFLECTIVE_PROFILES_REPOSITORY = Symbol('REFLECTIVE_PROFILES_REPOSITORY');
export const CHAT_AGENT = Symbol('CHAT_AGENT');
